### ISSUE TITLE
[Refactor] Having trouble with line 90 - check Content-Type

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#13]
can you see what is wrong? Not case is it?

```
C:\python35\lib\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Something went wrong: 'content-type'
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 90, in callResourceURI
    if 'application/json' in response.headers['content-type']:
  File "C:\python35\lib\site-packages\requests\structures.py", line 56, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'

Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 721, in validateURI
    SchemaSoup, refDict, SchemaFullType, 'entitytype')
  File "RedfishServiceValidator.py", line 210, in getTypeDetails
    for element in innerschema.find_all(tagType, attrs={'name': SchemaType}):
AttributeError: 'NoneType' object has no attribute 'find_all'

Validation has failed.

```*************here are the actual headers captured by chrome***************
HTTP/1.1 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-UA-Compatible: IE=11
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Content-Type: application/json
Transfer-Encoding: chunked
Date: Tue, 09 Feb 2016 22:26:09 GMT
Server: lighttpd/1.4.39

**Comment by tomasg2012** [comment]
Would it be ok if you provided the debug log?  callResourceURI's traceback isn't deep enough to tell where thiis is happening.

**Comment by tomasg2012** [comment]
The newest commit removes the password from the debug log, and attempted a few changes that might fix your problem, feel free to test then upload the log to a comment in this thread.

**Comment by jbobzin-insyde** [comment]
not seeing problem after update
