### ISSUE TITLE
Incorrect logger.info output line causes script to crash when using Session authentication

### ISSUE THREAD

**Issue by shinchley** [DMTF/Redfish-Service-Validator#272]
# python3 RedfishServiceValidator.py -c config.ini -v --schema_pack latest > output3.txt
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "RedfishServiceValidator.py", line 1391, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "RedfishServiceValidator.py", line 1282, in main
    currentService = rst.startService()
  File "/root/Redfish-Service-Validator-master/traverseService.py", line 89, in startService
    currentService = rfService(config)
  File "/root/Redfish-Service-Validator-master/traverseService.py", line 228, in __init__
    self.currentSession.startSession()
  File "/root/Redfish-Service-Validator-master/rfSession.py", line 55, in startSession
    self.logger.info('using default URI', sessionsURI)
Message: 'using default URI'
Arguments: ('/redfish/v1/SessionService/Sessions',)

Just need to format the variable into the string:

rfSessions.py Before:
            if sessionsObj is None:
                sessionsURI = '/redfish/v1/SessionService/Sessions'
                self.logger.info('using default URI',sessionsURI)
            else:

rfSessions.py After:
            if sessionsObj is None:
                sessionsURI = '/redfish/v1/SessionService/Sessions'
                self.logger.info('using default URI {}'.format(sessionsURI))
            else:

**Comment by mraineri** [comment]
PR merged
