### ISSUE TITLE
ERROR - Service could not be started: 'module' object is not callable   ( --authtype=Session )

### ISSUE THREAD

**Issue by gkeishin** [DMTF/Redfish-Service-Validator#408]
```
$ python3 RedfishServiceValidator.py --ip https://xx.xx.xx.xx:443 -u root -p ******** --logdir /tmp/redfish/ --debugging --authtype=Session -v
Redfish Service Validator, version 2.0.0

Writing config file to log directory
Target URI: https://xx.xx.xx.xx:443
authtype: Session
debugging: True
forceauth: False
ip: https://xx.xx.xx.xx:443
logdir: /tmp/redfish/
password: ******
schema_directory: ./SchemaFiles/metadata
username: root
verbose: 1
Start time: 08/09/21 - 00:51:51

Setting up service...
Service could not be started: 'module' object is not callable
```

```
$ cat /tmp/redfish/ConformanceLog_08_09_2021_005151.txt
INFO - Redfish Service Validator, version 2.0.0
INFO -
INFO - Writing config file to log directory
INFO - Target URI: https://xx.xx.xx.xx:443
INFO - authtype: Session
debugging: True
forceauth: False
ip: https://xx.xx.xx.xx:443
logdir: /tmp/redfish/
password: ******
schema_directory: ./SchemaFiles/metadata
username: root
verbose: 1
INFO - Start time: 08/09/21 - 00:51:51
INFO -
INFO - Setting up service...
DEBUG - Exception caught while creating Service
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 123, in main
    currentService = traverseService.startService(vars(args))
  File "/home/gkeishin/Redfish-Service-Validator/traverseService.py", line 60, in startService
    newService = rfService(config)
  File "/home/gkeishin/Redfish-Service-Validator/traverseService.py", line 110, in __init__
    self.currentSession = session(config['username'], config['password'], config['configuri'], None)
TypeError: 'module' object is not callable
ERROR - Service could not be started: 'module' object is not callable
```

**Comment by tomasg2012** [comment]
Was a small oversight.

Are you able to run the `rfsession-path-1` branch successfully?

**Comment by gkeishin** [comment]
I havent tried the fix.. Will check on it. .Thanks @tomasg2012

**Comment by gkeishin** [comment]
I pulled both the changes 
-  https://github.com/DMTF/Redfish-Service-Validator/pull/411
-  https://github.com/DMTF/Redfish-Service-Validator/pull/410

and re-ran and looking good

```
$ python3 RedfishServiceValidator.py --ip https://xx.xx.xx.xx:443 -u root -p ******* --logdir logs/ --authtype=Session
Redfish Service Validator, version 2.0.0

Writing config file to log directory
Target URI: https://xx.xx.xx.xx:443
authtype: Session
debugging: False
forceauth: False
ip: https://xx.xx.xx.xx:443
logdir: logs/
password: ******
schema_directory: ./SchemaFiles/metadata
username: root
verbose: 0
Start time: 08/09/21 - 08:25:20

Setting up service...
Session successfully created
Session successfully created
Constructing metadata...

...
...

*** /redfish/v1/JsonSchemas/redfish-schema
         Type (#JsonSchemaFile.v1_0_2.JsonSchemaFile), GET SUCCESS (time: 0.009844)
         PASS
Metadata: Namespaces missing from $metadata: set()

Elapsed time: 0:03:39
invalidPropertyValue: 46
metadataNamespaces: 2173
optionalAction: 8
pass: 3917
passAction: 11
passGet: 205
repeat: 1
serviceNamespaces: 64
skipOem: 530
skipOptional: 3549
warnDeprecated: 221
warningPresent: 34
Validation has succeeded.
```
