### ISSUE TITLE
Segmentation Fault with GUI

### ISSUE THREAD

**Issue by ShichenLin** [DMTF/Redfish-Service-Validator#447]
Other than issue #444, I also met a segmentation fault. The python backtrace I dumped with gdb is like the following:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff5eabe47 in ?? () from /usr/lib/x86_64-linux-gnu/libtk8.6.so
(gdb) py-bt
Traceback (most recent call first):
  <built-in method mainloop of _tkinter.tkapp object at remote 0x7ffff34364b0>
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)
  File "RedfishServiceValidatorGui.py", line 359, in main
    root.mainloop()
  File "RedfishServiceValidatorGui.py", line 362, in <module>
    main()
(gdb) thread 2
[Switching to thread 2 (Thread 0x7ffff2429700 (LWP 119768))]
#0  0x00007ffff7af8e1f in __GI___select (nfds=5, readfds=0x7ffff2428d30, writefds=0x7ffff2428db0, exceptfds=0x7ffff2428e30, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
41	../sysdeps/unix/sysv/linux/select.c: No such file or directory.
(gdb) thread 3
[Switching to thread 3 (Thread 0x7ffff1c28700 (LWP 121681))]
#0  0x00007ffff77d0ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x10c43e8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
88	../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
(gdb) py-bt
Traceback (most recent call first):
  <built-in method call of _tkinter.tkapp object at remote 0x7ffff34364b0>
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3341, in see
    self.tk.call(self._w, 'see', index)
  File "RedfishServiceValidatorGui.py", line 351, in write
    self.output.see( tk.END )
  File "/usr/lib/python3.6/logging/__init__.py", line 997, in emit
    stream.write(self.terminator)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1337, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 154, in validateSingleURI
    my_logger.error('URI {} does not match the following required URIs in Schema of {}'.format(odata_id, redfish_obj.Type))
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 280, in validateURITree
    validateSuccess, counts, results, links, thisobj = validateSingleURI(service, URI, uriName, expectedType, expectedJson, parent)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/shichenl/workspace/local/openbmc/Redfish-Service-Validator/RedfishServiceValidator.py", line 166, in main
    success, counts, results, xlinks, topobj = validateURITree(currentService, '/redfish/v1/', 'ServiceRoot', expectedJson=jsonData)
  File "RedfishServiceValidatorGui.py", line 295, in run_imp
    status_code, last_results_page, exit_string = rsv.main(configfile = rsv_config )
---Type <return> to continue, or q <return> to quit---
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
```

**Comment by mraineri** [comment]
For clarification, how are you running the tool? It looks like you're running the GUI applet, but might be running it via the command line.

And can you also confirm you're running 2.0.7 of the tool?

**Comment by ShichenLin** [comment]
Yes, I'm running 2.0.7 version. Like what you said, I was running `python3 RedfishServiceValidatorGui.py` from the command line, so am I not supposed to do that?

**Comment by mraineri** [comment]
You should be able to do that; just trying to make sure I'm looking in the right places.

I've been able to run it myself though like you have been (also with Python 3.6).

Are you encountering a similar problem if you run purely via command line options/output (with `RedfishServiceValidator.py`)?

**Comment by ShichenLin** [comment]
Pure command line runs with `RedfishServiceValidator.py` seem fine. I'm trying more runs now. The segmentation fault with GUI doesn't consistently happen, but it's pretty frequent at my side.

**Comment by mraineri** [comment]
Okay, thanks for the info; I'll do more testing on my end.

**Comment by mraineri** [comment]
@ShichenLin would it be possible to try newer versions of Python? I've been able to recreate this reliably on large services with Python3.6, but not with Python3.8. I've found similar issues reported with Python threading in other projects, but nothing too conclusive at the moment.

**Comment by ShichenLin** [comment]
Python3.8 seems to work fine for me. I agree that it's very likely to be some issue in 3.6.
