### ISSUE TITLE
Does it also support getting XML from the DMTF website？

### ISSUE THREAD

**Issue by haitaoso** [DMTF/Redfish-Service-Validator#467]
Referring to old version 1.4.1, this validator provides the feature that downloading XML files from redfish "/redfish/v1/$metadata" and the DMTF website based on reference. I think this feature is very convenient, we don't need to download DMTF's schema XML files manually.
```XML
<!-- /redfish/v1/schema/ServiceRoot_v1.xml-- >
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/KeyService_v1.xml">
        <edmx:Include Namespace="KeyService"/>
```
But the latest version 2.1.1, looks like it does not support downloading XML files from the DMTF website.
Is this a change to the architecture design layer in the "2. +" version? Is it still not supported in the future?

**Comment by mraineri** [comment]
At least if your SchemaFiles directory does not exist, it should be doing all of this automatically from now on; it will try to download the schema files from both the DMTF website and downloading local copies referenced by the service itself.

If you already have SchemaFiles in the tool's directory, can you delete it and try running the tool again to see if it buildings the schema cache?

**Comment by haitaoso** [comment]
It only downloads XML files from Redfish URI "/redfish/v1/$metadata", not downloads reference XML from DMTF website, such as the "KeyService_v1.xml".

**Comment by mraineri** [comment]
Could you please check the output from the tool (when the tool first creates the SchemaFiles directory)? It should state it's downloading the schema pack from the DMTF site as a starting point:

```
https://10.246.76.161 --mockup mockup
Redfish Service Validator, version 2.1.1

Writing config file to log directory
Target URI: https://10.246.76.161
authtype: Basic
debugging: False
forceauth: False
ip: https://10.246.76.161
logdir: ./logs
mockup: mockup
oemcheck: True
password: ******
schema_directory: ./SchemaFiles/metadata
uricheck: False
username: root
verbose: 0
Start time: 03/19/22 - 13:48:35

Downloading initial schemas from online
The tool will, by default, attempt to download and store XML files to relieve traffic from DMTF/service
Unpacking schema pack... https://www.dmtf.org/sites/default/files/standards/documents/DSP8010.zip
Setting up service..
```

The "DSP8010.zip" folder contains the contents of the "http://redfish.dmtf.org/schemas/v1/" directory on the DMTF site.

**Comment by tomasg2012** [comment]
Seems the tool might just expect you to delete the directory entirely to download the schemapack and xml files automatically.

**Comment by tomasg2012** [comment]
The tool itself is using an older piece of code for grabbing schema from the $metadata (schema.py), which is worth removing since catalog.py handles all the schema stuff, and grabbing the schema files from metadata should be simplified.

But the zip ought to be automatically grabbed if the directory does not exist or is manually deleted.  

It is undocumented, but running 

`python3 schema_pack.py`

should also grab the schemas for you.

**Comment by haitaoso** [comment]
OK! I reviewed the "schema_pack.py". Looks like it does not support setting network proxy for connecting DMTF website.
```python
# line 17-25
    proxies, timeout = None, 20
    if uri == 'latest':
        uri = live_zip_uri
    my_logger.info('Unpacking schema pack... {}'.format(uri))
    try:
        if not os.path.isdir(local_dir):
            os.makedirs(local_dir)
        response = requests.get(uri, timeout=timeout, proxies=proxies)
```
Can we add the proxy configuration?


And, some OEM redfish resource schema XML files need to be obtained from "$matadata". We need to preserve the mechanism for getting XML from $metadata

**Comment by mraineri** [comment]
Ah, good find. I would not expect the validator to be overriding the local proxy environment variables. The requests module has built in support for using the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. Do you have those variables configured?

After the tool downloads the 8010 zip file, it will go through $metadata to find additional schema files. Would you be able to delete the `proxies=proxies` input to `requests.get` and try again?

**Comment by haitaoso** [comment]
I tried again. it still report error:
```log
Downloading initial schemas from online
The tool will, by default, attempt to download and store XML files to relieve traffic from DMTF/service
Unpacking schema pack... https://www.dmtf.org/sites/default/files/standards/documents/DSP8010.zip      
A problem when getting resource has occurred https://www.dmtf.org/sites/default/files/standards/documents/DSP8010.zip
output: 
Traceback (most recent call last):
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 182, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002041A77F5F8>, 'Connection to www.dmtf.org timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 450, in send
    timeout=timeout
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.dmtf.org', port=443): Max retries exceeded with url: /sites/default/files/standards/documents/DSP8010.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002041A77F5F8>, 'Connection to www.dmtf.org timed out. (connect
 timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bmc_eval\Documents\Redfish-Service-Validator-master\schema_pack.py", line 26, in setup_schema_pack
    response = requests.get(uri, timeout=timeout)
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\bmc_eval\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.dmtf.org', port=443): Max retries exceeded with url: /sites/default/files/standards/documents/DSP8010.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002041A77F5F8>, 'Connection to www.dmtf.org timed out. (conne
ct timeout=20)'))
```

My configuration:
python: 3.6.8
requests: 2.27.1

Based on my experience, I think we need to add the http_proxy/https_proxy parameter like version 1.4.1, which is more convenient to use. can we?
```python
    argget.add_argument('--http_proxy', type=str, help='URL for the HTTP proxy')
    argget.add_argument('--https_proxy', type=str, help='URL for the HTTPS proxy')
```

**Comment by mraineri** [comment]
At the moment, there's no way to pass that into the Redfish library; the library is expecting environment variables to be configured to use proxies.

For the time being, can you set your environment variables? You should be able to do this on the command line prior to executing the tool like this:

```
set HTTPS_PROXY=https://....
set HTTP_PROXY=http://....
python3 RedfishServiceValidator.py ...
```

**Comment by haitaoso** [comment]
Yes, It works as you said.
Please update this line code:
```python
# schema_pack.py line:25
response = requests.get(uri, timeout=timeout, proxies=proxies)
```
