### ISSUE TITLE
I/O Error when logging errors from validateSingleURI function

### ISSUE THREAD

**Issue by hohene** [DMTF/Redfish-Service-Validator#66]
In RedfishServiceValidator.py, when trying to log the errors in "validateSingleURI" function, we get I/O operation failed due to error handler missing.   This is using version pulled 8/2/2017.  Need to add  rsvLogger.removeHandler(errh) before returns.  This causes the program to terminate on the error.

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
ValueError: I/O operation on closed file
Call stack:
  File "RedfishServiceValidator.py", line 811, in <module>
    sys.exit(main(sys.argv))
  File "RedfishServiceValidator.py", line 754, in main
    rsvLogger.error('{} {} errors in {}'.format(innerCounts[countType], countType, results[item][0].split(' ')[0]))
Message: '1 exceptionPropCompliance errors in /redfish/v1/TaskService'
Arguments: ()
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 811, in <module>
    sys.exit(main(sys.argv))
  File "RedfishServiceValidator.py", line 754, in main
    rsvLogger.error('{} {} errors in {}'.format(innerCounts[countType], countType, results[item][0].split(' ')[0]))
AttributeError: 'NoneType' object has no attribute 'split'
```

workaround I did:
Add rsvLogger.removeHandler(errh) before each return in validateSingleURI function.
```
diff --git a/RedfishServiceValidator.py b/RedfishServiceValidator.py
index 7b02c33..df0ec2d 100644
--- a/RedfishServiceValidator.py
+++ b/RedfishServiceValidator.py
@@ -529,12 +529,16 @@ def validateSingleURI(URI, uriName='', expectedType=None, expectedSchema=None, e
             success = False
             results[uriName] = (URI, success, counts, messages,
                                 errorMessages, None, None)
+            # EH
+            rsvLogger.removeHandler(errh)
             return False, counts, results, None, None
     except Exception as e:
         counts['exceptionResource'] += 1
         success = False
         results[uriName] = (URI, success, counts, messages,
                             errorMessages, None, None)
+        # EH
+        rsvLogger.removeHandler(errh)
         return False, counts, results, None, None
     counts['passGet'] += 1
     results[uriName] = (str(URI) + ' ({}s)'.format(propResourceObj.rtime), success, counts, messages, errorMessages, propResourceObj.context, propResourceObj.typeobj.fulltype)
```

**Comment by tomasg2012** [comment]
Hmm, interesting, I thought the code been handling this case but the line must've been lost when reworking those statement blocks.  Due to the nature in which the code captures errors for HTML output, this also has the secondary issue of throwing error lines in blocks they don't belong in.  Thank you for bringing this up!

**Comment by tomasg2012** [comment]
Should be fixed with latest 8-10 PR
