### ISSUE TITLE
Tool reporting ServiceRoot, /redfish/v1 is not returning XML or Json

### ISSUE THREAD

**Issue by hohene** [DMTF/Redfish-Service-Validator#83]
Have been running the RedfishServiceValidator tool against our server since June.  I updated to the latest code today (08/17) and am hitting failure as follows.  
```
python3 RedfishServiceValidator.py -c config/config.stack10 
System Info: RackHD
RedfishServiceValidator Config details: ('http://stack10-ora.admin:8080', 'user:admin', './SchemaFiles/metadata', 'no CheckCert', 'Attempt for Online Schema')
Start time: 08/17/17 - 18:57:21

*** ServiceRoot, /redfish/v1
This URI did NOT return XML or Json, this is not a Redfish resource (is this redirected?): /redfish/v1/$metadata

Traceback (most recent call last):
  File "/emc/hohene/redfish-tools/RAC-5818/EH1/RSV/traverseService.py", line 327, in getSchemaDetailsLocal
    filehandle = open(SchemaLocation + '/' + xml, "r")
FileNotFoundError: [Errno 2] No such file or directory: './SchemaFiles/metadata/$metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 547, in validateSingleURI
    uriName, URI, expectedType, expectedSchema, expectedJson, parent)
  File "/emc/hohene/redfish-tools/RAC-5818/EH1/RSV/traverseService.py", line 496, in __init__
    fullType, SchemaURI=self.context)
  File "/emc/hohene/redfish-tools/RAC-5818/EH1/RSV/traverseService.py", line 311, in getSchemaDetails
    return getSchemaDetailsLocal(SchemaAlias, SchemaURI)
  File "/emc/hohene/redfish-tools/RAC-5818/EH1/RSV/traverseService.py", line 355, in getSchemaDetailsLocal
    return getSchemaDetailsLocal(SchemaAlias, pout)
UnboundLocalError: local variable 'pout' referenced before assignment
Elapsed time: 0:00:00
1
1 exceptionResource errors in /redfish/v1
Counter({'exceptionResource': 1})
Validation has failed: 1 problems found
```

Fixing the un-initialized variable above, yields this:
```
python3 RedfishServiceValidator.py -c config/config.stack10
System Info: RackHD
RedfishServiceValidator Config details: ('http://stack10-ora.admin:8080', 'user:admin', './SchemaFiles/metadata', 'no CheckCert', 'Attempt for Online Schema')
Start time: 08/17/17 - 19:27:04

*** ServiceRoot, /redfish/v1
This URI did NOT return XML or Json, this is not a Redfish resource (is this redirected?): /redfish/v1/$metadata
Something went wrong
Traceback (most recent call last):
  File "/emc/hohene/redfish-tools/RAC-5818/EH1/RSV/traverseService.py", line 328, in getSchemaDetailsLocal
    filehandle = open(SchemaLocation + '/' + xml, "r")
FileNotFoundError: [Errno 2] No such file or directory: './SchemaFiles/metadata/$metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/emc/hohene/redfish-tools/RAC-5818/EH1/RSV/traverseService.py", line 328, in getSchemaDetailsLocal
    filehandle = open(SchemaLocation + '/' + xml, "r")
IsADirectoryError: [Errno 21] Is a directory: './SchemaFiles/metadata/'
validateURI: No schema XML for #ServiceRoot.v1_0_0.ServiceRoot
Elapsed time: 0:00:00
1
1 problemResource errors in /redfish/v1
Counter({'problemResource': 1})
Validation has failed: 1 problems found
```
The directory is present in ./SchemaFiles/metadata/<files>.
/redfish/v1 returns json data, but seems to not like it.  Will continue debugging.

**Comment by hohene** [comment]
Here's from the run prior to the tool update:
```
 python3 RedfishServiceValidator.py -c config/config.stack10 | more
System Info: RackHD
RedfishServiceValidator Config details: ('http://stack10-ora.admin:8080', 'user:admin', './SchemaFiles/metadata', 'no CheckCert', 'Attempt for Online Schema')
Start time: 08/17/17 - 20:42:03

*** ServiceRoot, /redfish/v1
ConfigURI: {} http://stack10-ora.admin:8080
URILink: {} /redfish/v1
 *********  SchemaURI:  /redfish/v1/$metadata#ServiceRoot.ServiceRoot
ConfigURI: {} http://stack10-ora.admin:8080
URILink: {} /redfish/v1/$metadata#ServiceRoot.ServiceRoot
 *********  SchemaURI:  /redfish/v1/Schemas/ServiceRoot_v1.xml
ConfigURI: {} http://stack10-ora.admin:8080
URILink: {} /redfish/v1/Schemas/ServiceRoot_v1.xml
 *********  SchemaURI:  /redfish/v1/$metadata
ConfigURI: {} http://stack10-ora.admin:8080
URILink: {} /redfish/v1/$metadata
Reference in a Schema containing ServiceRoot not in metadata, this may not be compatible with ServiceMode
References missing in metadata: ['StorageSystemCollection', 'FabricCollection', 'StorageServiceCollection', 'UpdateService', 'OData', 'Resource', 'Resource.v1_0_0', 'Redfish', 'Validation', 'Capabilities']
 *********  SchemaURI:  http://redfish.dmtf.org/schemas/v1/Resource_v1.xml
ConfigURI: {} http://stack10-ora.admin:8080
URILink: {} http://redfish.dmtf.org/schemas/v1/Resource_v1.xml
 *********  SchemaURI:  /redfish/v1/Schemas/ComputerSystemCollection_v1.xml
ConfigURI: {} http://stack10-ora.admin:8080
URILink: {} /redfish/v1/Schemas/ComputerSystemCollection_v1.xml
 *********  SchemaURI:  /redfish/v1/Schemas/ChassisCollection_v1.xml
ConfigURI: {} http://stack10-ora.admin:8080
```

**Comment by tomasg2012** [comment]
The correct behavior is that, if $metadata is unable to be found, then it should default to getting a local file based on the SchemaType of the payload.  This (and the unintialized variable) was just caught with the latest branch '8-18-usability'.

**Comment by hohene** [comment]
figured this out running with the debug version, thanks!  problem was in our code.
