### ISSUE TITLE
Exception after several hours

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#91]
Using the 8/31 code, had exception below

---> Assertion: 6.5.17

Expected property @odata.id in response body

Expected property @odata.id in response body

Expected property @odata.id in response body

Assertion Description: Resources in a response shall include a unique identifier property named "@odata.id". The value of the identifier property shall be the unique identifier for the resource.
<--- Assertion 6.5.17: FAIL

---> Assertion: 6.5.18

Traceback (most recent call last):
  File ".\rf_client.py", line 780, in <module>
    main()
  File ".\rf_client.py", line 774, in main
    rfs_test.run(sut)
  File "G:\_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test\__init__.py", line 39, in run
    TEST_protocol_details.run(sut, log)
  File "G:\_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 5040, in run
    assertion_status = Assertion_6_5_18(self, log)
  File "G:\_Redfish_git\Tools\Redfish-Service-Conformance\Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 3570, in Assertion_6_5_18
    if(json_payload is not None and '@odata.type' in json_payload and isinstance(json_payload['@odata.type'],basestring)) :
NameError: name 'basestring' is not defined

**Comment by peanutsandwich** [comment]
Hi Jeff,

Is this meant to be raised against the conformance tool rather than the validator?

I contributed a PR there recently that made this change for compatibility with Python 2, and it looks as though Python 3 removed the basestring type.

A solution for this would be to set 'basestring = str' or a try catch block around the offending code that catches the NameError and uses the alternative.

This would need to be done in the Python 3 branch at the top of the file.

I'm not going to be near a PC to be able to try and submit a commit for a little while, but will submit a change when I am able

**Comment by jbobzin-insyde** [comment]
Entered in the wrong repo
