### ISSUE TITLE
Exception thrown while parsing 'Links' attribute

### ISSUE THREAD

**Issue by veedu** [DMTF/Redfish-Service-Validator#97]
Exception gets thrown while parsing links attribute for properties as below:

Chassis.v1_0_0.Chassis:Links
        value: OrderedDict([('ComputerSystems@odata.navigationLink', '/redfish/v1/storage_systems'), ('Drives@odata.count', '3'), ('Drives@odata.navigationLink', '/redfish/v1/chassis/DN01/drives'), ('ManagedBy', [OrderedDict([('@odata.id', '/redfish/v1/managers/BMC')]), OrderedDict([('@odata.id', '/redfish/v1/managers/FPGA0')])]), ('ManagedBy@odata.count', 2)]) <class 'collections.OrderedDict'>
        has Type: Chassis.v1_0_0.Links complex
        is Optional
        is Nullable: false True
        Nullability test: OK
        ***going into Complex
Chassis.v1_4_0.Links:PCIeDevices
        value: n/a <class 'str'>
        has Type: Collection(PCIeDevice.PCIeDevice) entity
        is Optional
        prop Does not exist, skip...
Chassis.v1_2_0.Links:ManagersInChassis
        value: n/a <class 'str'>
        has Type: Collection(Manager.Manager) entity
        is Optional
        prop Does not exist, skip...
Chassis.v1_2_0.Links:Drives
        value: n/a <class 'str'>
        has Type: Collection(Drive.Drive) entity
        is Optional
        prop Does not exist, skip...
Chassis.v1_2_0.Links:Storage
        value: n/a <class 'str'>
        has Type: Collection(Storage.Storage) entity
        is Optional
        prop Does not exist, skip...
Chassis.v1_0_0.Links:ComputerSystems
        value: n/a <class 'str'>
        has Type: Collection(ComputerSystem.ComputerSystem) entity
        is Optional
        prop Does not exist, skip...
Chassis.v1_0_0.Links:ManagedBy
        value: [OrderedDict([('@odata.id', '/redfish/v1/managers/BMC')]), OrderedDict([('@odata.id', '/redfish/v1/managers/FPGA0')])] <class 'list'>
        has Type: Collection(Manager.Manager) entity
        is Optional
        is Collection
Something went wrong
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 570, in validateSingleURI
    propMessages, propCounts = checkPropertyCompliance(node.soup, prop.name, prop.propDict, propResourceObj.jsondata, node.refs)
  File "RedfishServiceValidator.py", line 406, in checkPropertyCompliance
    success, complexCounts, complexMessages = validateComplex(PropertyName, val, innerPropType, decoded.get('@odata.type'))
  File "RedfishServiceValidator.py", line 150, in validateComplex
    propMessages, propCounts = checkPropertyCompliance(propSoup, prop.name, prop.propDict, val, propRefs)
  File "RedfishServiceValidator.py", line 440, in checkPropertyCompliance
    paramPass = validateEntity(PropertyName, val, propType, propCollectionType, soup, refs, autoExpand)
  File "RedfishServiceValidator.py", line 88, in validateEntity
    currentType = data.get('@odata.type', propCollectionType)
AttributeError: 'str' object has no attribute 'get'
Chassis.v1_0_0.Chassis:Links:  Could not finish compliance check on this property

Also,

LinksOrderedDict([('Chassis', [OrderedDict([('@odata.id', '/redfish/v1/chassis/DN01')])]), ('Chassis@odata.count', 1), ('ManagedBy', [OrderedDict([('@odata.id', '/redfish/v1/managers/BMC')]), OrderedDict([('@odata.id', '/redfish/v1/managers/FPGA0')])]), ('ManagedBy@odata.count', 2)])-Exists (add.)- | Links | OrderedDict([('Chassis', [OrderedDict([('@odata.id', '/redfish/v1/chassis/DN01')])]), ('Chassis@odata.count', 1), ('ManagedBy', [OrderedDict([('@odata.id', '/redfish/v1/managers/BMC')]), OrderedDict([('@odata.id', '/redfish/v1/managers/FPGA0')])]), ('ManagedBy@odata.count', 2)]) | - | Exists (add.) | -
-- | -- | -- | -- | -- | --
Links | OrderedDict([('Chassis', [OrderedDict([('@odata.id', '/redfish/v1/chassis/DN01')])]), ('Chassis@odata.count', 1), ('ManagedBy', [OrderedDict([('@odata.id', '/redfish/v1/managers/BMC')]), OrderedDict([('@odata.id', '/redfish/v1/managers/FPGA0')])]), ('ManagedBy@odata.count', 2)]) | - | Exists (add.) | -
ERROR - Something went wrongTraceback (most recent call last):File "RedfishServiceValidator.py", line 570, in validateSingleURIpropMessages, propCounts = checkPropertyCompliance(node.soup, prop.name, prop.propDict, propResourceObj.jsondata, node.refs)File "RedfishServiceValidator.py", line 406, in checkPropertyCompliancesuccess, complexCounts, complexMessages = validateComplex(PropertyName, val, innerPropType, decoded.get('@odata.type'))File "RedfishServiceValidator.py", line 150, in validateComplexpropMessages, propCounts = checkPropertyCompliance(propSoup, prop.name, prop.propDict, val, propRefs)File "RedfishServiceValidator.py", line 440, in checkPropertyComplianceparamPass = validateEntity(PropertyName, val, propType, propCollectionType, soup, refs, autoExpand)File "RedfishServiceValidator.py", line 88, in validateEntitycurrentType = data.get('@odata.type', propCollectionType)AttributeError: 'str' object has no attribute 'get'ERROR - #ComputerSystem.ComputerSystem:Links: Could not finish compliance check on this property

Please help us with the above issue.

Thanks,
Vidhya G

**Comment by tomasg2012** [comment]
Seems that there's something unusual about the FPGA0 or BMC resources, off my first impression, data at this part of the control flow should be a payload...  Could you post the payload associated with `/redfish/v1/managers/FPGA0` and `BMC`?  Is there any missing or unusual headers?

**Comment by tomasg2012** [comment]
@veedu, could you comment on this again?  Also with the last issue you added #95 ?

**Comment by mraineri** [comment]
@veedu any chance you could please provide @tomasg2012 with the requested info?

**Comment by mraineri** [comment]
1/11: Closing; no activity on the issue
